[package]
name = "redis-cluster"
version = "0.1.0"
authors = ["Francis Tseng <f@frnsys.com>"]
description = "Interface to Redis Cluster"
repository = "https://github.com/frnsys/redis-cluster.rs"
license = "MIT"

[dependencies]
rand = "0.3"
redis = "0.5.3"

